name: CI

on:
  push:
    branches: [main]
    tags: ["coverage-p-*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements_build.txt

    - name: Build
      # Isolation is disabled so that the pinned dependencies are used.
      run: python -m build --wheel --no-isolation --skip-dependency-check

    - run: twine check dist/*.*

    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*.whl

  test:
    runs-on: ubuntu-24.04
    name: ${{ matrix.python-version }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "pypy3.10"

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - uses: actions/download-artifact@v5
      with:
        name: dist
        path: dist/

    - name: Test
      run: python test.py

  pypi-publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/coverage-p-')
    needs: [build, test]

    environment:
      name: release
      url: https://pypi.org/p/coverage-p

    permissions:
      id-token: write

    steps:

    - uses: actions/download-artifact@v5
      with:
        name: dist
        path: dist/

    - uses: pypa/gh-action-pypi-publish@release/v1
