name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  pypi-publish:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/coveragepth-') }}

    environment: release
    permissions:
      id-token: write

    steps:

    - uses: actions/download-artifact@v4
      with:
        name: dist-3.12
        path: dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
